### ISSUE TITLE
bomb_rectとrect_bg

### ISSUE THREAD

**Issue by c0119177** [c0a2106090/ProjExD#13]
https://github.com/c0a2106090/ProjExD/blob/a624ba3a0352e7c667e2bee5510d7b3d963cd266/ex04/dodge_bomb.py#L36

bomb_rectとrect_bgの比較をすればスクリーンサイズに関わらずに反射できる

**Comment by c0a2106090** [comment]
実数してするのきれいじゃないし感謝です
